[build]
  command = "npx quartz build"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/auth"
  status = 200
  force = true
  conditions = {Role = ["!authenticated"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
